/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wdg.interestsystem.view;

import com.wdg.interestsystem.controller.InterestDAO;
import com.wdg.interestsystem.controller.InterestDAOImp;
import com.wdg.interestsystem.model.Customer;
import com.wdg.interestsystem.model.Interest;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author acer
 */
public class InterestManagement extends javax.swing.JPanel {

    /**
     * Creates new form InterestManagement
     */
    
    DefaultComboBoxModel customerModel = new DefaultComboBoxModel();

    public InterestManagement() {
        initComponents();
   //  cmbName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));


        
        txtID.setVisible(false);
        InterestTable.setSelectionModel(new InterestManagement.ForcedListSelectionModel());
        InterestTable.setRowHeight(24);
        InterestTable.setFont(new Font("Dialog", Font.BOLD, 16));

        JTableHeader header = InterestTable.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 18));
        //customerTable.setFont(new Font("Serif", Font.BOLD, 20));

        //Fill the name combo box
        fillCombobox();
        
       // loadList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTelOne = new javax.swing.JTextField();
        txtInstallment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtInterest = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InterestTable = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        cmbName = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNew.setText("New");

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setText("Edit");

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdd.setText("Insert");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Description :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Date :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 70, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Interest Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 40));

        txtTelOne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtTelOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 286, 32));

        txtInstallment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtInstallment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 286, 32));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Amount :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Interest :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, 40));

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 286, 32));

        txtInterest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 286, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Installment :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, 30));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 360, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 70, 30));

        InterestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Date", "Amount", "Interest", "Installment", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Double.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(InterestTable);
        if (InterestTable.getColumnModel().getColumnCount() > 0) {
            InterestTable.getColumnModel().getColumn(0).setMinWidth(40);
            InterestTable.getColumnModel().getColumn(0).setMaxWidth(50);
            InterestTable.getColumnModel().getColumn(1).setMinWidth(200);
            InterestTable.getColumnModel().getColumn(1).setMaxWidth(230);
            InterestTable.getColumnModel().getColumn(2).setMinWidth(100);
            InterestTable.getColumnModel().getColumn(2).setMaxWidth(150);
            InterestTable.getColumnModel().getColumn(3).setMinWidth(120);
            InterestTable.getColumnModel().getColumn(3).setMaxWidth(150);
            InterestTable.getColumnModel().getColumn(4).setMinWidth(80);
            InterestTable.getColumnModel().getColumn(4).setMaxWidth(100);
            InterestTable.getColumnModel().getColumn(5).setMinWidth(120);
            InterestTable.getColumnModel().getColumn(5).setMaxWidth(150);
            InterestTable.getColumnModel().getColumn(6).setMinWidth(300);
            InterestTable.getColumnModel().getColumn(6).setMaxWidth(320);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 920, 210));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 90, -1));

        cmbName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(cmbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 460, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

    private void loadList() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void fillCombobox() {

        //Clear combobox
     cmbName.removeAllItems();
     cmbName.addItem("Select Category");
        InterestDAO intImp = new InterestDAOImp();

        List<Customer> list = intImp.fillCustomer();
        
        //cmbName.setModel(new javax.swing.DefaultComboBoxModel());

       // customerModel.removeAllElements();
        //Add data to combo box
       for (Customer result : list){
           //customerModel.addElement(result);
            cmbName.addItem(result);
           }

       //cmbName.setModel(customerModel);

    }

    public class ForcedListSelectionModel extends DefaultListSelectionModel {

        public ForcedListSelectionModel() {
            setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }

        @Override
        public void clearSelection() {
        }

        @Override
        public void removeSelectionInterval(int index0, int index1) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InterestTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInstallment;
    private javax.swing.JTextField txtInterest;
    private javax.swing.JTextField txtTelOne;
    // End of variables declaration//GEN-END:variables
}
