/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wdg.interestsystem.view;

import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BoxLayout;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class JFrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    //Creating the initial requirements
    GridBagLayout gbl = new GridBagLayout();
    CustomerRegistration customerManagement;
    InterestManagement interestManagement;
    GridBagConstraints c;
    //ExpenceManager exManager;

    public JFrameHome() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        changeDynamicPanel("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        btnInterestManagement = new javax.swing.JButton();
        btnCustomerManagement = new javax.swing.JButton();
        dynamicPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        menuManagement = new javax.swing.JMenu();
        menuCustomerManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(214, 209, 205));

        btnInterestManagement.setBackground(new java.awt.Color(175, 164, 154));
        btnInterestManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInterestManagement.setForeground(new java.awt.Color(108, 91, 84));
        btnInterestManagement.setText("Interest Managment");
        btnInterestManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInterestManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterestManagementActionPerformed(evt);
            }
        });

        btnCustomerManagement.setBackground(new java.awt.Color(175, 164, 154));
        btnCustomerManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCustomerManagement.setForeground(new java.awt.Color(108, 91, 84));
        btnCustomerManagement.setText("Customer Management");
        btnCustomerManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInterestManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnCustomerManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnInterestManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(579, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftPanelLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(btnCustomerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(647, Short.MAX_VALUE)))
        );

        getContentPane().add(leftPanel, java.awt.BorderLayout.LINE_START);

        dynamicPanel.setBackground(new java.awt.Color(230, 210, 193));
        getContentPane().add(dynamicPanel, java.awt.BorderLayout.CENTER);

        menuFile.setText("Menu");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuManagement.setText("Management");

        menuCustomerManagement.setText("Customer Management");
        menuCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerManagementActionPerformed(evt);
            }
        });
        menuManagement.add(menuCustomerManagement);

        jMenuBar1.add(menuManagement);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_menuExitActionPerformed

    private void menuCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerManagementActionPerformed

        /*
        FrameCustomerManagemet frameCustomerManagement = new FrameCustomerManagemet();
        desktopPane.add(frameCustomerManagement);
        frameCustomerManagement.setVisible(true);
         */

    }//GEN-LAST:event_menuCustomerManagementActionPerformed

    private void btnCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagementActionPerformed

        changeDynamicPanel("customer");

		}//GEN-LAST:event_btnCustomerManagementActionPerformed

    private void btnInterestManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterestManagementActionPerformed

        changeDynamicPanel("interest");

		}//GEN-LAST:event_btnInterestManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    public void changeDynamicPanel(String page) {

        /*
        if(customerManagement != null){
        customerManagement.setVisible(false);
        interestManagement.setVisible(false);
        dynamicPanel.removeAll();

        }
*/
        customerManagement = null;
        interestManagement = null;


        c = null;
        dynamicPanel.setLayout(gbl);
        c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;

        c.gridx = 0;
        c.gridy = 0;

        switch (page) {
            case "customer":
                System.out.println("called");
                customerManagement = null;
                customerManagement = new CustomerRegistration();
                dynamicPanel.add(customerManagement, c);
                customerManagement.setVisible(true);

                break;
            case "interest":
                interestManagement = null;
                interestManagement = new InterestManagement();
                dynamicPanel.add(interestManagement, c);
                interestManagement.setVisible(true);
                break;
            case "dateView":

                break;
            default:
                customerManagement = null;
                customerManagement = new CustomerRegistration();
                dynamicPanel.add(customerManagement, c);
                customerManagement.setVisible(true);
                break;

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerManagement;
    private javax.swing.JButton btnInterestManagement;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JMenuItem menuCustomerManagement;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuManagement;
    // End of variables declaration//GEN-END:variables
}
